# Normalización y Estandarización.

* La normalización y estandarizacion **son técnicas útiles de preprocesamiento de datos** porque **pueden ayudar a mejorar el rendimiento** de muchos modelos de aprendizaje automático. 

* Por ejemplo, algunos modelos de aprendizaje automático **pueden ser sensibles a la escala de los datos y pueden rendir mejor cuando los datos están reescalados o normalizados.** 

* También pueden ser útiles para **hacer que los datos sean más fáciles de visualizar o comparar.**

---
## Pautas que pueden ayudarte a decidir si debes utilizar la estandarización o la normalización

**Utiliza la normalización si:**

1. Necesitas que los valores de las características o variables estén en el rango de valores (0, 1).

2. Si los algoritmos de aprendizaje automático que estás utilizando son sensibles a la escala de las características o variables.

**Utiliza la estandarización si:**

1. Necesitas que los valores de las características o variables tengan **media 0 y desviación estándar 1.**

2. Si las características o variables tienen **diferentes unidades de medida o tienen una escala muy diferente.**

3. Si las **características o variables tienen distribuciones muy diferentes.**

4. Si los algoritmos de aprendizaje automático que estás utilizando son sensibles a la escala de las características o variables.

A continuación vamos a estudiar como aplicar Normalización y estandarización a nuestros datos.

---
# Normalización

* La normalización es una **técnica de preprocesamiento de datos que consiste en ajustar los valores de los datos a un rango específico.** 

* Por ejemplo, es común reescalar los datos para que estén en el rango de **0 a 1.** Esto se puede hacer utilizando la siguiente fórmula:

**`x_rescaled = (x - x_min) / (x_max - x_min)`**


Donde **`x` es el valor original, `x_min` es el valor mínimo del conjunto de datos y `x_max` es el valor máximo del conjunto de datos.** Esta fórmula ajusta los valores de x para que estén en el rango de 0 a 1.

In [1]:
import numpy as np
# Creamos una matriz de datos X con 3 caracteristicas numéricas(columnas)
x = np.array([[2, 3, 5],
              [6, 2, 4],
              [1, 4, 3],
              [8, 5, 1],
              [3, 6, 2],
              [5, 7, 4],
              [9, 3, 6],
              [7, 2, 5],
              [4, 1, 3],
              [2, 8, 4]], dtype=np.float32)

In [3]:


#Queremos normalizar cada caracteristica de la matriz (cada columna).
#Para ello tenemos que recorrer cada columna, sacar el minimo, el máximo y luego aplicar el metodo interp
#El reescalado sigue la siguiente formula: x_rescaled = (x - x_min) / (x_max - x_min).

# Recorremos cada columna de la matriz X
for i in range(x.shape[1]):
    # Calculamos el valor mínimo y máximo de la columna
    x_min = np.min(x[:, i])
    x_max = np.max(x[:, i])
    
    # Normalizamos la columna
    x[:, i] = np.interp(x[:, i], (x_min, x_max), (0, 1))

# Si quisiera redondear, podria:
#para cada fila le aplico un map con una función lambda que redonde a 4 decimales.
#a modo ejercicio lo podemos hacer pero en los reescalados y normalizaciones no hay que hacerlo.
#x = [ list( map(lambda x: round(x,4),fila) ) for fila in x ]

El código anterior normalizará cada columna de la matriz x para que esté en el rango de 0 a 1. El resultado final sería una matriz x reescalada, que se vería así:

In [4]:
x

array([[0.125     , 0.2857143 , 0.8       ],
       [0.625     , 0.14285715, 0.6       ],
       [0.        , 0.42857143, 0.4       ],
       [0.875     , 0.5714286 , 0.        ],
       [0.25      , 0.71428573, 0.2       ],
       [0.5       , 0.85714287, 0.6       ],
       [1.        , 0.2857143 , 1.        ],
       [0.75      , 0.14285715, 0.8       ],
       [0.375     , 0.        , 0.4       ],
       [0.125     , 1.        , 0.6       ]], dtype=float32)

## Ejemplo Real de Uso



Imaginemos que tenemos un conjunto de datos que contiene información sobre diferentes propiedades inmobiliarias, **como el tamaño en metros cuadrados, el número de habitaciones, el precio y la ubicación.** Si queremos utilizar un algoritmo de aprendizaje automático para **predecir el precio de las propiedades en función de sus características,** es posible que deseemos **normalizar alguna de las características para mejorar la precisión de nuestro modelo.**

Por ejemplo, si queremos **normalizar el tamaño en metros cuadrados** de las propiedades, podemos utilizar la siguiente fórmula:

In [ ]:
size_norm = (size - size_min) / (size_max - size_min)

Donde `size` es el tamaño original de la propiedad en metros cuadrados, `size_min` es el tamaño mínimo de las propiedades en el conjunto de datos, y `size_max` es el tamaño máximo de las propiedades en el conjunto de datos.

Con esta fórmula, podemos transformar el tamaño de cada propiedad en un valor normalizado entre 0 y 1, lo que puede ser útil para mejorar la precisión de nuestro modelo de aprendizaje automático.

In [6]:
import pandas as pd

df_madrid = pd.read_csv('../11Libreria_Pandas/data/Pisos_Madrid.csv')
df_madrid.head()

,web_id,url,title,type,price,deposit,private_owner,professional_name,floor_built,floor_area,...,terrace,balcony,storeroom,swimming_pool,garden_area,location,district,subdistrict,postalcode,last_update
0,99439319,https://www.idealista.com/en/inmueble/99439319/,"Flat / apartment for rent in pablo luna, 4",Flat,1400,NaN,False,Silcasas Ochocientas,60,NaN,...,True,False,False,False,False,"pablo luna, 4, Subdistrict Castilla, District ...",Chamartín,Castilla,28046.0,7 November
1,99439586,https://www.idealista.com/en/inmueble/99439586/,Penthouse for rent in calle de Bolivia,Penthouse,1300,1.0,False,Cruzity,77,NaN,...,False,False,False,False,False,"Calle de Bolivia, Subdistrict Bernabéu-Hispano...",Chamartín,Bernabéu-Hispanoamérica,28016.0,7 November
2,99439169,https://www.idealista.com/en/inmueble/99439169/,Duplex for rent in calle de la constancia,Duplex,950,1.0,False,Mm Home,72,68.0,...,True,False,False,False,False,"Calle de la constancia, Urb. no, Subdistrict P...",Chamartín,Prosperidad,28002.0,7 November
3,26925909,https://www.idealista.com/en/inmueble/26925909/,"Flat / apartment for rent in Urb. el viso, El ...",Flat,2975,1.0,False,B&H Partners,160,NaN,...,True,False,False,True,False,"Urb. el viso, Subdistrict El Viso, District Ch...",Chamartín,El Viso,NaN,7 November
4,99440018,https://www.idealista.com/en/inmueble/99440018/,Studio flat for rent in luis cabrera,Studio,650,1.0,False,Madrid en Propiedad,30,NaN,...,False,True,False,False,False,"luis cabrera, Subdistrict Prosperidad, Distric...",Chamartín,Prosperidad,28002.0,7 November


In [10]:
def normalizar_columna(columna):
    minimo = np.min(columna)
    maximo = np.max(columna)
    return np.interp(columna, (minimo, maximo), (0, 1))

def normalizar_columna2(columna):
    minimo = np.min(columna)
    maximo = np.max(columna)
    #(size - size_min) / (size_max - size_min)
    return (columna - minimo) / (maximo -minimo)

In [12]:
df_madrid['floor_built'] = normalizar_columna(df_madrid['floor_built']) 
df_madrid['floor_built']

0       0.060606
1       0.077778
2       0.072727
3       0.161616
4       0.030303
          ...   
9224    0.095960
9225    0.070707
9226    0.168687
9227    0.056566
9228    0.056566
Name: floor_built, Length: 9229, dtype: float64

In [13]:
df_madrid['floor_built2'] = normalizar_columna2(df_madrid['floor_built'])
df_madrid['floor_built2'] 

0       0.060606
1       0.077778
2       0.072727
3       0.161616
4       0.030303
          ...   
9224    0.095960
9225    0.070707
9226    0.168687
9227    0.056566
9228    0.056566
Name: floor_built2, Length: 9229, dtype: float64

---
# Estandarización

* La Estandarización es otra técnica de preprocesamiento de datos que **consiste en transformar los datos de tal manera que tengan una distribución normal (o gaussiana)** con una media de 0 y una desviación estándar de 1. 

* Esto se puede hacer utilizando la siguiente fórmula:

**x_estandarizado = (x - x_mean) / x_std**

* Donde x es el valor original, `x_mean` es la media del conjunto de datos y `x_std` es la desviación estándar del conjunto de datos. Esta fórmula ajusta los valores de x para que tengan una media de 0 y una desviación estándar de 1.

Para estandarizar los datos, podemos utilizar la fórmula de estandarización mencionada anteriormente y aplicarla a cada columna de la matriz X de la misma manera que hicimos con la normalización. 

**Vamos a ver un ejemplo de código que realiza la estandarización de los datos:**

In [2]:
import numpy as np

# Creamos una matriz de datos X
X = np.array([[2, 3, 5],
              [6, 2, 4],
              [1, 4, 3],
              [8, 5, 1],
              [3, 6, 2],
              [5, 7, 4],
              [9, 3, 6],
              [7, 2, 5],
              [4, 1, 3],
              [2, 8, 4]], dtype=np.float32)

# Recorremos cada columna de la matriz X
for i in range(X.shape[1]):
    # Calculamos la media y la desviación estándar de la columna
    x_mean = np.mean(X[:, i])
    x_std = np.std(X[:, i])
    
    # estandarizamos la columna
    X[:, i] = (X[:, i] - x_mean) / x_std

print(X)

[[-1.0346422  -0.49743715  0.9169493 ]
 [ 0.49816117 -0.9496528   0.21160366]
 [-1.417843   -0.04522152 -0.493742  ]
 [ 1.2645628   0.4069941  -1.9044333 ]
 [-0.65144134  0.8592097  -1.1990876 ]
 [ 0.11496032  1.3114253   0.21160366]
 [ 1.6477636  -0.49743715  1.6222949 ]
 [ 0.88136196 -0.9496528   0.9169493 ]
 [-0.2682405  -1.4018683  -0.493742  ]
 [-1.0346422   1.763641    0.21160366]]


## Ejemplo de Uso Real

Imaginemos que tenemos un conjunto de datos que contiene **información sobre diferentes estudiantes de una escuela, como su edad, su altura, su peso y su promedio en el último examen.** Si queremos utilizar un algoritmo de aprendizaje automático para **predecir el promedio en el próximo examen en función de las otras características de los estudiantes,** es posible que deseemos **estandarizar alguna de las características para mejorar la precisión de nuestro modelo.**

Por ejemplo, si queremos **estandarizar la edad de los estudiantes,** podemos utilizar la siguiente fórmula:

In [ ]:
age_std = (age - age_mean) / age_std

Donde `age` es la edad original del estudiante, `age_mean` es la media de la edad de los estudiantes en el conjunto de datos, y `age_std` es la desviación estándar de la edad de los estudiantes en el conjunto de datos.

Con esta fórmula, podemos **transformar la edad de cada estudiante en un valor estandarizado,** lo que puede ser útil para **mejorar la precisión de nuestro modelo de aprendizaje automático.**

# ¿ Es conveniente aplicar redondeos a las variables o caracteristicas tras realizar una estandarización o normalización?

En general, **no es conveniente redondear los valores de las características o variables tras realizar una estadarización o normalización, ya que el redondeo puede afectar la precisión y la calidad de los resultados.**

La estandarización y la normalización **son técnicas utilizadas para transformar los valores de las características o variables** de un conjunto de datos de manera que **cumplan ciertas condiciones,** como tener un rango de valores específico o tener una media y una desviación estándar determinadas. **Al redondear los valores de las características o variables,estamos alterando los valores originales y, por tanto, también estamos alterando la transformación realizada.**

En cambio, si queremos trabajar con valores redondeados, podemos hacerlo antes de aplicar la estandarización o la normalización, utilizando la función `numpy.round()` o cualquier otra función de redondeo. De esta manera, estamos trabajando con valores redondeados desde el principio y no afectamos la precisión de la transformación realizada.