![numpy.png](https://drive.google.com/uc?id=1cT4dkZxwEmHg5gkusiVbEwLf4QYyOnEt)

## <div class="alert alert-info"> <center> NumPy - Vectores y Matrices </div>


---
### 1. ¿Qué es NumPy?

**NumPy es el paquete fundamental para la computación científica en Python.** Es una biblioteca de Python que proporciona un objeto de array multidimensional, varios objetos derivados (como arrays y matrices) y **una variedad de rutinas para operaciones rápidas en matrices, que incluyen manipulación matemática, lógica, de formas, clasificación, selección,  álgebra lineal básica, operaciones estadísticas básicas, simulación aleatoria y mucho más.**

---
### <mark>1.1 ¿Cuál es la diferencia entre una lista de Python y una matriz NumPy?</mark>


* NumPy nos brinda una **enorme variedad de formas rápidas y eficientes de crear matrices y manipular datos numéricos** dentro de ellas. 


* Si bien una lista de Python puede contener diferentes tipos de datos dentro de una sola lista, **todos los elementos de un array NumPy deben ser homogéneos.** 


* Las operaciones matemáticas que deben realizarse en Arrays serían **extremadamente ineficientes si los Arrays no fueran homogéneos.**



### <mark>1.2 ¿Por qué usar NumPy?</mark>

* Los Arrays NumPy son más rápidos y compactos que las listas de Python. 


* **Un Array NumPy usa mucha menos memoria para almacenar datos** y proporciona un mecanismo para especificar los tipos de datos. Esto permite **optimizar** aún más el código.


**<div class="alert alert-info"> Los puntos sobre el tamaño y la velocidad de la secuencia son particularmente importantes en la computación científica.  </div>**

### <mark>1.3 ¿Por qué NumPy es rápido?</mark> 

La vectorización (el código se parece más a las expresiones matemáticas) describe la **ausencia de bucles explícitos, indexación, etc.,** en el código; estas cosas están ocurriendo "detrás de escena" en código C optimizado y precompilado(numpy está escrito en C). 

El código vectorizado tiene muchas ventajas, entre las que se encuentran:

* El código vectorizado es **más conciso y más fácil de leer.**


* **Menos líneas de código generalmente significan menos errores.**


* El código se parece más a la **notación matemática estándar** (lo que facilita, por lo general, codificar correctamente las construcciones matemáticas).


* La vectorización da como resultado código más "Pythonic". Sin la vectorización, nuestro código estaría plagado de bucles for ineficientes y difíciles de leer.

Numpy tiene muuuuuuchas funciones integradas. No las veremos todas, nos centraremos en algunos de los aspectos que más se utilizan: 
**<div class="alert alert-success"> <center> vectores, matrices y generación de números.</div>**

---
### 2. Instalando e Importando Numpy

Si estás trabajando con Google Colab o tenemos Anaconda, NumPy ya viene instalado, pero en caso de que no lo esté, podemos instalarlo en el CMD o terminal con:

**pip install numpy o conda install numpy.**

También podemos hacerlo desde una celda de colab o de jupyter notebook con:

**!pip install numpy**

In [ ]:
#probemos si lo tenemos instalado 
!pip install numpy

Una vez lo tenemos instalado podemos importarlo así:    

In [1]:
import numpy as np# esta es la convención estandar al importar numpy

---
### 3. Arrays en Numpy


**Un Array es la estructura de datos central de la biblioteca NumPy.** 

El Array es una cuadrícula de valores y contiene información sobre los datos sin procesar, cómo ubicar un elemento y cómo interpretarlo.


Ocasionalmente, es posible que escuches que se hace referencia a un Array como "ndarray", que es la abreviatura de "array N-dimensional". 
**<div class="alert alert-info"> Un Array N-dimensional es simplemente un Array con cualquier número de dimensiones. </div>**
 

También podemos escuchar 1-D o Array unidimensional, 2-D o Array bidimensional, etc. La clase NumPy ndarray se usa para representar matrices y vectores. Un **vector** es un Array con una sola dimensión (no hay diferencia entre vectores de fila y columna), mientras que una **matriz** se refiere a un Array con dos dimensiones. Para Arrays tridimensionales o de mayor dimensión, el término **tensor** también se usa comúnmente.


**<div class="alert alert-warning">En resumen:</div>**

* **Vector:** es un Array de una sola dimension o 1-D Array

* **Matriz:** es un Array de 2 dimensiones o 2-D Array

* **Arrays Ndimensionales o Tensores:**  3-D, 4-D, 5-D...



### <mark>3.1 ¿Cuáles son los atributos de un Array?</mark>

Un Array suele ser un contenedor de tamaño fijo de elementos del mismo tipo y tamaño. 

Los atributos de cualquier Array son:

* **Número de elementos (size)**

* **Dimension (ndim)**

* **Estructura (shape).** Es una tupla de enteros no negativos que especifican los tamaños de cada dimensión.


**En NumPy, las dimensiones se llaman ejes. Esto significa que si tenemos un Array 2D que se ve así:**

[[0., 0., 0.],

 [1., 1., 1.]]
 
 **Esta matriz tiene 2 ejes. El primer eje tiene una longitud de 2 y el segundo eje tiene una longitud de 3.**

![1D_2D.PNG](https://drive.google.com/uc?id=1oyl0nN2tGeEfMw90wHHHQkqMT0onCSu5)

![3D1.PNG](https://drive.google.com/uc?id=1ZusgKhggkDyMWqUTNWOYlxEoVKmrCYna)



In [2]:
array3d = np.arange(24).reshape(4,3,2)

print(array3d)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]




![3D-2.PNG](https://drive.google.com/uc?id=1t-ERvCNOAXU1Aa0IloPcUBkADW5yEY0E)


---
### 4. Cómo crear un Array básico

Para crear un Array NumPy, podemos usar la función **np.array().**

Todo lo que necesitamos hacer para crear un Array simple es pasarle una lista. También puedes especificar el tipo de datos con el parámetro dtype.
[Tipos de datos arrays NumPy](https://numpy.org/doc/stable/reference/arrays.dtypes.html#)

In [33]:
import numpy as np
a = np.array([1, 2, 3])
print(f"Array 1D: {a}")

Array 1D: [1 2 3]


In [32]:
np.dtype('i2')

dtype('int16')

![np_array.png](https://drive.google.com/uc?id=18qUZJLy5HnqKZGJBK35qV4ihNYiQI1wr)

In [34]:
data = np.array([[1, 2], [3, 4], [5, 6]])
print(f"Array 2D o Matriz:\n{data}")

Array 2D o Matriz:
[[1 2]
 [3 4]
 [5 6]]


![np_create_matrix.png](https://drive.google.com/uc?id=1Wbq3u8FtdOB-UgFe00tG6T7h3hDQ0S5E)

In [37]:
b = np.array([1, 2, 3], dtype='U')
b

array(['1', '2', '3'], dtype='<U1')

Podemos ver los atributos de un array con:


In [38]:
print(f"Numero de elementos: {b.size}")
print(f"Número de dimensiones: {b.ndim}")
print(f"Estructura: {b.shape}")

Numero de elementos: 3
Número de dimensiones: 1
Estructura: (3,)


In [39]:
print(f"Numero de elementos: {data.size}")
print(f"Número de dimensiones: {data.ndim}")
print(f"Estructura: {data.shape}")

Numero de elementos: 6
Número de dimensiones: 2
Estructura: (3, 2)


### <mark>4.1 Seleccionando elementos de un array</mark>

Utilizamos la misma nomenclatura que en las listas, tuplas, sets de python o los vectores y matrices de otros lenguajes. Usamos los [ ].

Veamos algunos ejemplos con arrays de distintas dimensiones.

In [51]:
#definimos los Arrays
#1D
b = np.array([1, 2, 3, 4, 5])

#2D
c = np.array([
    [1, 2, 3], [4, 5, 6]
])

#3D
d = np.array([
    [
        [1, 2, 3], [4, 5, 6]
    ], 
    [
        [4, 4, 4], [4, 5, 6]
    ]
])

#4D
e = np.array([
    [
        [[1, 2, 3], [4, 5, 6]], 
        [[1, 2, 3], [4, 5, 6]],
        [[1, 2, 3], [4, 5, 6]], 
        [[1, 2, 3], [4, 5, 6]]
    ]
])

In [41]:
print(b)

[1 2 3 4 5]


In [42]:
print(c)

[[1 2 3]
 [4 5 6]]


In [43]:
print(d)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [44]:
print(e)

[[[[1 2 3]
   [4 5 6]]

  [[1 2 3]
   [4 5 6]]

  [[1 2 3]
   [4 5 6]]

  [[1 2 3]
   [4 5 6]]]]


In [ ]:
#selecciona el tercer elemento del array b(recuerda que los indices empiezan en 0)
b[2]

NameError: name 'b' is not defined

In [46]:
#primera fila del array c
c[0]

array([1, 2, 3])

In [47]:
#segundo elemento de la segunda fila del array c (el 5)
c[1][1]

5

In [48]:
#selecciona el elemento 6 del array c
c[1][2]

6

In [52]:
#segundo elemento del array d
print(d[1])

#valor 6 del array d[1]
d[1][1][2]

[[4 4 4]
 [4 5 6]]


6

In [53]:
#primer elemento del array d
e[0][0][0][0]

1

### <mark>4.2 Recorriendo elementos de un array</mark>

**<div class="alert alert-info"> Arrays 1D </div>**

Necesitamos un solo índice para recorrer los elementos

In [54]:
for i in range(b.size):
    print(f"Indice: {i} --> Valor: {b[i]}")

Indice: 0 --> Valor: 1
Indice: 1 --> Valor: 2
Indice: 2 --> Valor: 3
Indice: 3 --> Valor: 4
Indice: 4 --> Valor: 5


**<div class="alert alert-info"> Arrays 2D </div>**

Necesitamos 2 índices para recorrer los elementos

In [55]:
filas = c.shape[0]
columnas = c.shape[1]

print(c.shape)
print(f"Filas:{filas}")
print(f"Columnas:{columnas}")

for i in range(filas):
    for j in range(columnas):
        print(f"Fila:{i}, Columna:{j} --> Valor: {c[i][j]}")

(2, 3)
Filas:2
Columnas:3
Fila:0, Columna:0 --> Valor: 1
Fila:0, Columna:1 --> Valor: 2
Fila:0, Columna:2 --> Valor: 3
Fila:1, Columna:0 --> Valor: 4
Fila:1, Columna:1 --> Valor: 5
Fila:1, Columna:2 --> Valor: 6


**<div class="alert alert-info"> Arrays 3D </div>**

Necesitamos 3 índices para recorrer todos los elementos.

In [ ]:
#Implementa un fragmento de código que te permita recorrer los arrays d y e.


---
### 5. Crear Arrays desde distintas estructuras de Python

Una forma en que podemos inicializar las matrices NumPy es desde las estructuras de Python(listas, tuplas, diccionarios).


### <mark>5.1 Lista como Array</mark>

Podemos crear un array desde una lista o desde una lista de listas. Veamos como sería:

In [57]:
milista = [1, 2, 3, 4]
milista

[1, 2, 3, 4]

In [58]:
np.array(milista) #conversion de una lista a array mediante el metodo 'array'

array([1, 2, 3, 4])

In [59]:
a = np.array(milista)#podemos asignarlo a una variable

print(type(a))#ver el tipo que es a

a.dtype#tipo de datos que contiene el array

<class 'numpy.ndarray'>


dtype('int32')

In [60]:
mi_matriz = [[1,2,3],[4,5,6],[7,8,9]] # Una lista de listas (matriz de toda la vida de dios)
mi_matriz

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [61]:
np.array(mi_matriz) # conversion de una lista de listas a Matriz Numpy en este caso matriz 2D de 3 filas x 3 columnas(3x3 de toda la vida de dios)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [62]:
b = np.array(mi_matriz) # aasginar la conversion a una variable
type(b) # tipo de dato

numpy.ndarray

### <mark>5.2 Tupla como array</mark>

In [63]:
mi_tupla = (1, 58, 63, 45)
print(type(mi_tupla))

<class 'tuple'>


In [64]:
arr_tuple = np.array(mi_tupla)

print(arr_tuple)
print(type(arr_tuple))

[ 1 58 63 45]
<class 'numpy.ndarray'>


### <mark>5.3 Diccionario como array</mark>

In [65]:
my_dict = {'one': 'uno', 
           'two': 'dos',
           'three': 'tres'}

In [66]:
arr_dict = np.array(my_dict)
print(type(arr_dict))

<class 'numpy.ndarray'>


In [67]:
arr_dict

array({'one': 'uno', 'two': 'dos', 'three': 'tres'}, dtype=object)

**Mejor pasarlo antes a lista...**

In [68]:
dict_list = list(my_dict.items())
print(dict_list)

[('one', 'uno'), ('two', 'dos'), ('three', 'tres')]


In [69]:
arr_dict = np.array(dict_list)
print(arr_dict)

[['one' 'uno']
 ['two' 'dos']
 ['three' 'tres']]


In [70]:
arr_dict[0]

array(['one', 'uno'], dtype='<U5')

---
### 6. Generación Arrays y Matrices

Existen infinidad de funciones para generar arrays y matrices

### <mark>6.1 Métodos Integrados (Built-in Methods)</mark>

### 6.1.1 arange - Generar un array de enteros entre un rango

Devuelve **valores espaciados uniformemente dentro de un intervalo dado.** Es muy parecida a la funcion range de las basicas de python.

In [71]:
# generar un array de enteros desde 0 hasta 9, recordar que el valor final no se incluye
np.arange(0,10)  # arange(valor_inicial,valor_final-1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [72]:
np.arange(2, 9, 2)#valores entre el 2 y el 9, incrementando de 2 en dos

array([2, 4, 6, 8])

### 6.1.2 zeros y ones

Para generar arrays de 0s y 1s. 

In [73]:
np.zeros(3) # Generar un array de ceros que contenga 3 elementos

array([0., 0., 0.])

In [74]:
np.zeros((5,5),dtype='I') # Generar una matriz de ceros de 5 x 5 elementos

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=uint32)

In [75]:
np.ones(3) # Generar un array de unos que contenga 3 elementos

array([1., 1., 1.])

In [78]:
np.ones((3,3),dtype='I') # Generar una matriz de unos de 5 x 5 elementos

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=uint32)

### 6.1.3 linspace

Devuelve **números espaciados uniformemente** durante un intervalo especificado.

In [83]:
# Generar 3 valores iniciando en 0 y terminando en 10 (incluyendolo)
np.linspace(0,10,2) # linspace(valor_inicial, valor_final, numero_de_elementos)

array([ 0., 10.])

In [79]:
# Generar 50 valores iniciando en 0 y terminando en 10 (incluyendolo)
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

### 6.1.4 eye - Matriz de Identidad

Crea la matriz e identidad.

In [84]:
np.eye(4) # crea la matriz identidad de 4x4 elementos

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### 6.1.5 Diag - Diagonal del array

Muestra la diagonal del array

In [85]:
aux = np.array([
    [1, 8, 5],
    [2, 4, 0]
])

np.diag(aux)

array([1, 4])

In [86]:
aux = np.array([
    [1, 8, 5],
    [2, 4, 0],
    [3, 8, 8]
])

np.diag(aux)

array([1, 4, 8])

También permite crear la diagonal

In [87]:
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

### <div style = 'background-color:SKYBLUE'> <center> EJERCICIOS </div>

### Ejercicio 6.1.1 

Genera un Array 1D con números entre el 55 y el 67, ambos incluidos.

### Ejercicio 6.1.2 

Genera un Array 2D de 4x3 de unos.

### Ejercicio 6.1.3

Generar 4 valores enteros separados uniformemente iniciando en 10 y terminando en 25 (incluyendolo)

### Ejercicio 6.1.4 

1. Genera la matriz de idendidad de un array 2D de 3x3

2. Crea un array 2D con la diagonal 5, 7, 9, 11 


### Ejercicio 6.1.5

Crea un vector de 10 posiciones de ceros. Actualiza la posición 6 con el valor 11.


### Ejercicio 6.1.6

Crea una función que nos diga si existe el elemento 0 en un array:

Datos de pruebas:

x = np.array([1, 2, 3, 4])

y = np.array([0, 1, 2, 3, 4, 5, 6])

### Ejercicio 6.1.7

Crea un array de 10 ceros, 10 unos, 10 cincos. Únelos todos en un array 2D.


### <mark>6.2 Numeros Aleatorios (Random)</mark>

Numpy tiene diferentes formas de crear arrays de numeros aleatorios, el modulo para realizar esto se llama **Random**

### 6.2.1 rand

Crea un array de la forma dada y la rellena con muestras aleatorias de una distribución uniforme sobre [0, 1).

**Algunos tipos de Distribuciones**

![distribuciones.png](https://drive.google.com/uc?id=12fFOk28OkJY1EdpfP5OUrbDKYTRn_VSm)

In [ ]:
# creacion de un array de 2 elementos 1 una dimension
np.random.rand(2) #Los numeros aleatorios seran de una distribucion uniforme

In [ ]:
# creacion de una matriz de 5x5
np.random.rand(5,5) #Los numeros aleatorios seran de una distribucion uniforme

**Vamos a hacer una pequeña comprobación para ver que la distribución efectivamente es uniforme**

In [ ]:
import matplotlib.pyplot as plt #utilizamos matplotlib para graficar, lo veremos con más detalle en capitulos posteriores.

#nos permite insertar gráficos dentro del notebook.
%matplotlib inline

In [ ]:
x = np.random.rand(100)#genera 100 valores aleatorios con distribución uniforme

In [ ]:
plt.hist(x)
plt.show()

### 6.2.2 randn

**Devuelve una muestra (o muestras) de la distribución “estándar normal”.** A diferencia del rand que es uniforme. Genera valores aleatorios entre -4 y 4 pero la mayoria de estos se concentran entre -1 y 1.


**<div class="alert alert-info"> Nota: acordaros de la n final de randn para saber que es de nomal (distribución normal) </div>**

In [ ]:
# creacion de un array de 2 elementos 1 una dimension
np.random.randn(2) #Los numeros aleatorios seran de una distribucion "estándar normal"

**¿Comprobamos si efectivamente los números aleatorios generados tienen una distribución normal?**

In [ ]:
x = np.random.randn(1000000)#genera 1 millon de valores con distribución normal
plt.hist(x)
plt.show()

### 6.2.3 randint

Entrega numeros enteros aleatorios desde inicio (inclusivo) hasta final (exclusivo).

In [ ]:
np.random.randint(1,100) # Genera un numero aleatorio entre 1 y 99

In [ ]:
np.random.randint(1,100,(10,2)) # Genera una matriz de 10x2 elementos con valores aleatorios entre 1 y 99

### <div style = 'background-color:skyblue'> <center> EJERCICIOS </div>

### Ejercicio 6.2.1

Programa que muestre un array de 15 valores aleatorios que signa una distribución normal.

#### Solución

### Ejercicio 6.2.2

Escribe una matriz de 3x3x3 con valores aleatorios.

#### Solución

### Ejercicio 6.2.3

Crea un array de todos los enteros pares del 30 al 70.


---
### 7. Métodos para Añadir, Eliminar y Ordenar

### <mark>7.1 Añadir Elementos Al Final- Append(...)</mark>

Método que ofrece Numpy para agregar elementos al final de un array. Tiene la siguiente forma:

**np.append(arr, values, axis=None)**


* arr: es un array de Numpy.
* values: son los valores que se agregan al final del array que se pasa en el parámetro anterior. Este elemento puede ser también un array de Numpy.
* axis: es el **eje opcional en el que se agregan los valores.**

**<div class="alert alert-danger">Importante</div>**

El método no modifica el array original, sino que crea una copia a la que le agrega los nuevos valores.

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
b = np.append(arr, 10)
print(f"Array Original: {arr}")
print(f"Array Modificado: {b}")

Array Original: [1 2 3 4 5]
Array Modificado: [ 1  2  3  4  5 10]


**Tambien podemos agregar otro Array**

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
arrb = np.array([10,11])
np.append(arr,arrb)

array([ 1,  2,  3,  4,  5, 10, 11])

**Axis**

Si no se indica un valor para axis y arr es una matriz, el objeto **se aplanará antes de agregar los nuevos elementos.** Siendo las posibles opciones de este parámetro:

* 0: los valores se agregarán en el eje 0, es decir, **axis = 0 agregará nuevas filas.**

* 1: los valores se agregarán en el eje 1, es decir, **axis = 1 agregará nuevas columnas.**

**Agregar elementos al final en Arrays 2D o matrices**

Además de con arrays 1D el método **np.append() también se puede emplear en matrices.** Como hemos comentado anteriormente es necesario indicar mediante el **parámetro axis si los nuevos elementos se agregan por filas o columnas.** 

En el caso de que no se indique el parámetro la matriz se aplanara antes de agregar los elementos, obteniéndose como resultado un array. Esto es lo que vamos a ver en el siguiente ejemplo:

In [ ]:
#vamos a probar lo que acabamos de comentar. Creamos una matriz y agregamos una lista de valores sin indicar axis
matriz = np.array([
                    [1,2,3],
                    [4,5,6],
                    [7,8,9]
                ])
print(matriz)

matrizb = np.append(matriz, [10,11,12])#no indicamos nada y aplana la matriz.
print(matrizb)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


**Vamos a agregar una nueva fila**

In [ ]:
#ahora vamos a indicarle donde queremos añadir. axis= 0 para agregar una nueva fila
matrizc = np.append(matriz, [[10,11,12]], axis=0)#axis0
print(matrizc)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


**Ahora vamos a agregar una nueva columna (axis=1)**

In [ ]:
matrizd = np.append(matriz, [[10],[11],[12]], axis=1)#axis1
print(matrizd)

[[ 1  2  3 10]
 [ 4  5  6 11]
 [ 7  8  9 12]]


### <mark>7.2 Insertar elemento en una Posición en Concreto - Insert(...)</mark>

Podemos insertar nuevos elementos en una posición en concreto de un Array. La forma de hacerlo es la siguiente:

**np.insert(arr, obj, values, axis=None)**

Siendo arr el array donde insertar los nuevos valores

obj la posicion a partir de la cual insertar

values los valores

axis el eje que se va a tener en cuenta para insertar. Por defecto viene a None.

**Returns:** Devuelve un nuevo array copia de arr con los valores insertados

In [ ]:
a = np.array([[1, 1], [2, 2], [3, 3]])
a

array([[1, 1],
       [2, 2],
       [3, 3]])

In [ ]:
#insertamos en la posición 1 el elemento 5. Como no indicamos eje, aplana el Array 2D e inserta en la pos 1
np.insert(a, 1, 5)

array([1, 5, 1, 2, 2, 3, 3])

In [ ]:
print(a)

[[1 1]
 [2 2]
 [3 3]]


Utilicemos ahora axis para insertar en la matriz

In [ ]:
np.insert(a, 1, 5, axis=1)

array([[1, 5, 1],
       [2, 5, 2],
       [3, 5, 3]])

Si quisiera añadir una columna que no tuviera el mismo valor en cada posición, lo haría así:

In [ ]:
b = np.insert(a, [1], [[1],[2],[3]], axis=1)
b

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [ ]:
np.insert(a, 1, (5,6,7), axis=1)

array([[1, 5, 1],
       [2, 6, 2],
       [3, 7, 3]])

Vamos a insertar ahora varios elementos a partir de una posición

In [ ]:
c = np.array([1, 5, 1, 2, 2, 3, 3])
c

array([1, 5, 1, 2, 2, 3, 3])

In [ ]:
np.insert(c, [0], [8, 6])

array([8, 6, 1, 5, 1, 2, 2, 3, 3])

### <mark>7.3 concatenate(...)</mark>

Podemos usar el método concatenate para concatenar vectores y matrices

In [ ]:
#si tenemos los arrays 1D
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

#Podemos concatenarlos con:
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

O si tenemos estas matrices:
    

In [ ]:
x = np.array([[1, 2], [3, 4]]) #matriz 2x2 (2 filas x 2 columnas)
y = np.array([[5, 6]])#matriz 1x2 (1 fila x 2 columnas)

#podemos concatenarlas con:
np.concatenate((x, y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

### <mark>7.4 Eliminar elementos - Delete(...)</mark>

El método acepta tres parámetros:arr, obj y axis y devuelve un array NumPy. 

* Arr es el **array NumPy de la que deseamos eliminar elementos.** 


* Obj es una **lista de números enteros con los índices de los elementos que deben eliminarse del array.** 


* Axis es un argumento opcional. Se refiere al **eje a lo largo del cual los elementos seleccionados por el obj deben eliminarse.** 

    * Si se asigna un valor None a este parámetro, arr se aplana y se lleva a cabo la eliminación en esta matriz aplanada.

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
indices = [3, 5, 7]#posiciones del indice que quiero borrar 
a_modificado = np.delete(a, indices) #ahora le paso al método delete los indices a borrar
print(a_modificado)

[ 1  2  3  5  7  9 10]


In [ ]:
print(matriz) #para ver sobre lo que vamos a trabajar
#borra los indices 1 y 2 del eje 0.
#muestra la matriz antes y despues del borrado


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
indices = [1,2]
matriz_borrada = np.delete(matriz, indices,axis=0)
print(f"Matriz original:\n {matriz}")
print(f"Matriz sin las filas {indices}:\n{matriz_borrada}")


Matriz original:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Matriz sin las filas [1, 2]:
[[1 2 3]]


In [ ]:
#vamos a eliminar ahora columnas. Dada la siguiente matriz, elimina las columnas 1 y 2
mimatriz = np.array([[1, 2, 3, 4, 5], [11, 12, 13, 14, 15], [21, 22, 23, 24, 25]])
print(mimatriz)

#añade el código aquí


[[ 1  2  3  4  5]
 [11 12 13 14 15]
 [21 22 23 24 25]]


In [ ]:
indices = [1,2]
matriz_borrada = np.delete(mimatriz, indices,axis=1)
print(f"Matriz original:\n {mimatriz}")
print(f"Matriz sin las filas {indices}:\n{matriz_borrada}")

Matriz original:
 [[ 1  2  3  4  5]
 [11 12 13 14 15]
 [21 22 23 24 25]]
Matriz sin las filas [1, 2]:
[[ 1  4  5]
 [11 14 15]
 [21 24 25]]


**Elimina ahora los elementos 1 y 2 sin indicar el parámetro axis.**

¿Qué valores ha eliminado?


In [ ]:
indices = [1,2]
np.delete(mimatriz,indices)

array([ 1,  4,  5, 11, 12, 13, 14, 15, 21, 22, 23, 24, 25])

### <mark>7.4.1 Eliminar Duplicados</mark>

Dado el siguiente Array 2D. Averigua dos formas de eliminar los duplicados

**data = np.array([10,10,20,20,30,30 ]**
            
![unique.PNG](https://drive.google.com/uc?id=10a4yORHPjebuA_ifO4zDQ_q4nc5JHykH)            
                 
*********************************************************************                 

**Ahora dada la siguiente matriz, elimina los duplicados:**

1. En cada fila. El resultado debe ser una matriz en la que no haya duplicados por filas.

2. En toda la matriz. El resultado debe ser un array 1d sin duplicados.

In [ ]:
data = np.array([[5,8,2,2,5],
                 [5,0,9,9,6],
                 [1,1,3,4,7]])


### <mark>7.4 Ordenar elementos - Sort(...)</mark>

Método que devuelve una copia ordenada del Array.

Forma de usarlo:

**np.sort(a, axis=-1, order=None)**

* a - Es el array a ordenar

* axis - eje que se debe tener en cuenta para ordenar el array. Es opcional. Si no se pone nada, el array ordena por el último eje, si se le indica None, se aplana y luego se ordena.

* order: parámetro opcional, para indicarle el campo por el que queremos ordenar.

**Vamos a ver algunos ejemplos de como funciona este método.**

In [ ]:
a = np.array([[1,4, 5],[3,1, 6], [9,2,6]])
a

array([[1, 4, 5],
       [3, 1, 6],
       [9, 2, 6]])

In [ ]:
np.sort(a)#ordena por axis=1(ultimo eje)

array([[1, 4, 5],
       [1, 3, 6],
       [2, 6, 9]])

In [ ]:
np.sort(a, axis=0)#ordena por el primer eje

array([[1, 1, 5],
       [3, 2, 6],
       [9, 4, 6]])

In [ ]:
np.sort(a, axis=None)

array([1, 1, 2, 3, 4, 5, 6, 6, 9])

Vamos a ver ahora un ejemplo en el que le indiquemos por qué campo ordenar.

In [ ]:
data_type = [('nombre', 'U30'), ('clase', int), ('altura', float)]
detalles_estudiantes = [('Jaime Pinillo', 5, 178.5), ('Macarena', 6, 172.5),('Pablo Escobar', 5, 172.5), ('Pit Samptras', 5, 185.1)]
# creamos la estructura array de estudiantes
estudiantes = np.array(detalles_estudiantes, dtype=data_type) 
print(type(estudiantes))
print("Array original:")
print(estudiantes)
print("Ordenado por altura")

print(np.sort(estudiantes, order=['altura','clase'])) #puedo ordenar por varios criterios?

<class 'numpy.ndarray'>
Array original:
[('Jaime Pinillo', 5, 178.5) ('Macarena', 6, 172.5)
 ('Pablo Escobar', 5, 172.5) ('Pit Samptras', 5, 185.1)]
Ordenado por altura
[('Pablo Escobar', 5, 172.5) ('Macarena', 6, 172.5)
 ('Jaime Pinillo', 5, 178.5) ('Pit Samptras', 5, 185.1)]


### <div style = 'background-color:skyblue'> <center> 7.5 EJERCICIOS </div>

### Ejercicio 1

a = np.array([1, 2, 3, 4, 5])
b = np.array([[10,40],[30,20], [50,60]])


Dados los arrays a y b, realizada las operaciones siguientes:

1. Añade al final de a el elemento 8.

2. Añade en la posición 2 del array a los elementos 7 y 9.

3. En el array b, añade antes de la primera columna los valores [-1,-2,-3]

4. En el array b, añade una nueva columna en la posición 2.

5. Al final del array b, agrega una nueva fila.

#### Solución:

### Ejercicio 2

Dadas las listas:

a = [9, 6, 3, 0, -3]

b = [10, 8, 6, 4, 2]

Concatenalas en un array 2D de 2X5 

#### Solución:

### Ejercicio 3

Dado el array 2D:

[[ 6 57 50 67 67],

 [90 26 50 13 60],
 
 [62 36 91 75  6],
 
 [92 67 94 62 44],
 
 [69 33 91 67 6]]

Elimina la columna 1 y 2 y todos los duplicados que queden en la matriz.

#### Solución:

### Ejercicio 4

Dada la siguiente lista de tuplas con nombres, altura y edad, transformala a un array y ordenalo por altura y edad (ascendente)

values = [('Cayo Julio César', 1.67, 41), ('Publio Cornelio Escipion', 1.67, 38),('Anibal Barca', 1.8, 54), ('Vercingetorix', 1.9, 29 ) ('Marco Ulpio Trajano', 1.7, 38)]


#### Solución:

---
### 8. Caracteristicas del Array (Forma, Tamaño, Dimensiones, Max, Min, Tipo...)

In [ ]:
#Vamos a generar un array con el que realizar pruebas.

arr = np.arange(25) #Genera un array de numeros enteros del 0 al 24
ranarr = np.random.randint(0,50,10) #Genera un array de 10 elementosdel 0 al 49

print(arr)
print(type(arr))
print(ranarr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
<class 'numpy.ndarray'>
[11 41 38 12 36 17  7 42  7 29]


### <mark>8.1 max,min,argmax,argmin</mark>

Estos son métodos útiles para encontrar valores máximos o mínimos. O para encontrar el indice de ubicaciones usando argmin o argmax

In [ ]:
ranarr

array([11, 41, 38, 12, 36, 17,  7, 42,  7, 29])

In [ ]:
ranarr.max() # Valor maximo del array

42

In [ ]:
ranarr.min() # Valor minimo del array

7

In [ ]:
ranarr.argmax() # Posicion del valor maximo del array (recordar que empieza en cero)
#si no se le indica eje, aplana el array y saca su posición

1

In [ ]:
ranarr.argmin() # Posicion del valor minimo del array (recordar que empieza en cero)
#si no se le indica eje, aplana el array y saca su posición

9

Probemos con un array 2D

In [ ]:
#creamos un array 2D para jugar con los min, max
data = np.array([[1, 2], [5, 3], [4, 6]])
print(data)


[[1 2]
 [5 3]
 [4 6]]


In [ ]:
print(data.max())
print(data.min())

6
1


![max_min.PNG](https://drive.google.com/uc?id=1PZxzBfYdQD6aOJbmH55_ULGh4s1x5otE)

Podemos sacar el max y min teniendo en cuenta los ejes:

In [ ]:
data = np.array([[1, 2], [5, 3], [4, 6]])
data

array([[1, 2],
       [5, 3],
       [4, 6]])

![np_matrix_aggregation_row.png](https://drive.google.com/uc?id=1mdXDVg98HoiDmryKqAsV14TW5KbgGrPs)

In [ ]:
print(data)
print(data.max(axis=0))
print(data.max(axis=1))

[[1 2]
 [5 3]
 [4 6]]
[5 6]
[2 5 6]


### <mark>8.2 Shape</mark>

Shape es un attributo para **ver la forma o estructura del array (No es metodo) y nos devuelve la siguiente información:**


* (__longitud elementos dim 1__, __longitud elementos dim 2__,..., __longitud elementos dim n__)



In [ ]:
# Vector
arr.shape

(25,)

**<div class="alert alert-danger">Importante</div>**

Los reshape **no cambia el vector original,** simplemente se **muestra en pantalla una reestructuración.** Si queremos crear un nuevo array con esa disposición tendremos que copiarlo con el método copy()

### Pregunta.

¿Cuál será la estructura `shape` de este array? (Sin usar Shape)

In [ ]:
import numpy as np
pregunta = np.array([
    [
        [1, 10, 100, 1000],
        [2, 20, 200, 2000],
        [3, 30, 300, 3000]
    ],
    [
        [4, 40, 400, 4000],
        [5, 50, 500, 5000],
        [6, 60, 600, 6000]
    ], 
    [
        [7, 70, 700, 7000],
        [8, 80, 800, 8000],
        [9, 90, 900, 9000]
    ]
])
print(pregunta)

[[[   1   10  100 1000]
  [   2   20  200 2000]
  [   3   30  300 3000]]

 [[   4   40  400 4000]
  [   5   50  500 5000]
  [   6   60  600 6000]]

 [[   7   70  700 7000]
  [   8   80  800 8000]
  [   9   90  900 9000]]]


In [ ]:
pregunta.shape

(3, 3, 4)

### <mark>8.3 dtype</mark>

Para obtener los tipos de datos dentro del array:

In [ ]:
arr.dtype

dtype('int32')

### <mark>8.4 size</mark>

Número de elementos en un Array

In [ ]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))
arr_2d.size

9

### <mark>8.5 ndim</mark>

Número de dimensiones del Array o matriz.

**Vamos a crear 4 arrays de distintas dimensiones...**

In [ ]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([
    [1, 2, 3], [4, 5, 6]
    ])
d = np.array([
    [
        [1, 2, 3], [4, 5, 6]
    ], 
    [
        [1, 2, 3], [4, 5, 6]
    ]
])
e = np.array([
    [
        [[1, 2, 3], [4, 5, 6]], 
        [[1, 2, 3], [4, 5, 6]],
        [[1, 2, 3], [4, 5, 6]], 
        [[1, 2, 3], [4, 5, 6]]
    ]
])

In [ ]:
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)
print(e.ndim)

0
1
2
3
4


### <div style = 'background-color:skyblue'> <center> 8.6 EJERCICIOS </div>

### Ejercicio 1

Dado el array:

data2 = np.array([  

                [5, 2, 3, 6],                
                [4, 5, 6, 4],                
                [3, 6, 5, 3],                
                [6, 5, 6, 5]                
                ])
1. Averigua cual es su estructura, dimensión, tamaño y tipo de datos de sus elementos. Representalo todo de forma clara identificando cada característica.

2. Muesta el pantalla el elemento mayor y menor del array así como su posición.

3. Muestra los mayores y menores por filas y columnas.

4. Averigua como mostrar la posición de los mayores y menores de cada fila y columna.

---
### 9. Indexacion y Seleccion de rangos (Slicing) en NumPy

Como indexar y seleccionar elementos o grupos de elementos de un array

In [3]:
import numpy as np

In [4]:
#Creando un arreglo de ejemplo
arr = np.arange(0,11) # Generar un arreglo de enteros del 0 hasta el 10

In [5]:
arr.dtype # tipos de datos dentro del arreglo

dtype('int32')

### <mark>9.1 Indexación y Slicing de Arrays 1D</mark>

Podemos indexar y dividir Arrays NumPy de la misma manera que puede dividir listas de Python.

In [6]:
data = np.arange(20)
print(data)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [7]:
# Obtener un valor conociendo su indice (index)
data[8]

8

In [8]:
#Obtener los valores en un rango [valor_inicial, valor_final -1]
data[1:5]

array([1, 2, 3, 4])

In [9]:
#Obtener los valores en un rango [valor_inicial, valor_final -1] por ejemplo desde 0-5
data[0:5]

array([0, 1, 2, 3, 4])

In [12]:
#desde el 1 hasta el final
data[1:-1]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18])

In [14]:
#desde el penultimo hasta el final. Como sería?
data[-2:]

array([18, 19])

De inicio a 9 de tres en tres elementos

In [17]:
data[:10:3] # De inicio a 9 de tres en tres elementos

array([0, 3, 6, 9])

De 6 a fin de dos en dos elementos

In [18]:
data[6::2] # De 6 a fin de dos en dos elementos

array([ 6,  8, 10, 12, 14, 16, 18])

De inicio hasta el elemento -3 del array

In [19]:
data[:-3] # De inicio hasta el elemento -3 del array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

Array reverso

In [20]:
data[::-1]

array([19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,
        2,  1,  0])

De fin (reverso) a inicio tomados de 2 en 2

In [21]:
#como sería?
data[::-2]

array([19, 17, 15, 13, 11,  9,  7,  5,  3,  1])

### <div style = 'background-color:skyblue'> <center> 9.1.1 EJERCICIOS </div>


Del array data:

1. Quedate con los elementos comprendidos entre la posición 4 y 7.

2. Quedate con los elementos desde el antepenultimo hasta el final.

3. Quedate con los elementos desde el cuarto empezando por el final hasta el décimo empezando por atrás.

4. Quedate con los elementos de inicio a 15 de 5 en 5 elementos.

5. Quedate con los elementos de inicio hasta el elemento 7 empezando por el final del array.

#### soluciones:

### <mark>9.2 Indexación y Slicing de Arrays 2D</mark>

El formato general es **arr_2d[fila][col]** o **arr_2d[fila,col].** 


<font color='green'>**Se recomienda usar la notacion con la coma por claridad.**</font>

In [22]:
# Creacion de una matriz de 3x3
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

print(arr_2d)

[[ 5 10 15]
 [20 25 30]
 [35 40 45]]


In [23]:
#Indexando por filas
arr_2d[1] # Obtener la fila 1 (recordar que el indice de python empieza en 0)

array([20, 25, 30])

In [24]:
# El formato es **arr_2d[fila][col]** o **arr_2d[fila,col]**

# Obteniendo un elemento en especifico
print(arr_2d[1][0]) # elemento de la fila 1 columna 0
print(arr_2d[1,0])

20
20


In [25]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [26]:
# seleccion de rangos en Arrays 2D (slicing)

#dimensiones (2,2) desde la esquina superior derecha
arr_2d[:2,1:] # filas [0,1](el 2 no está incluido) y columnas 1 hasta el final. 

#¿Qué valores mostrará?

array([[10, 15],
       [25, 30]])

In [27]:
# fila de indice 2
arr_2d[2]

array([35, 40, 45])

In [28]:
# todos los elementos de las columnas que estan en la fila de posicion 2
arr_2d[2,:]

array([35, 40, 45])

In [29]:
a = np.array([
             [0,  1,  2,  3,  4,  5],
             [10, 11, 12, 13, 14, 15],
             [20, 21, 22, 23, 24, 25],
             [30, 31, 32, 33, 34, 35],
             [40, 41, 42, 43, 44, 45],
             [50, 51, 52, 53, 54, 55]])
print(a)

[[ 0  1  2  3  4  5]
 [10 11 12 13 14 15]
 [20 21 22 23 24 25]
 [30 31 32 33 34 35]
 [40 41 42 43 44 45]
 [50 51 52 53 54 55]]


In [30]:
#quiero la fila 1 y recorrer su elementos de 2 en dos
a[1:2, ::2] #--> filas 1 a 2(2 sin incluir). Columnas: desde inicio a fin, y el 2 indica que saltamos de dos en dos.

array([[10, 12, 14]])

In [31]:
#columna 1 de 3 en tres
a[::3, 1:2]

array([[ 1],
       [31]])

In [32]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [33]:
#ahora quiero los elementos de las columnas 2 y 3 de dos en dos y en orden inverso.
a[::-2, 2:4]

array([[52, 53],
       [32, 33],
       [12, 13]])

### Ayudas para indexacion

La indexación de una matriz 2D puede ser un poco confusa al principio, especialmente cuando comienza a agregar pasos en la seleccion. La mejor forma de verlo es graficamente:



![ayuda_index.png](https://drive.google.com/uc?id=1E3evR9Jk2Nz67l2CaQ1l64OUZqMcAvol)

### <div style = 'background-color:skyblue'> <center>9.2.1 EJERCICIOS </div>

Dado el array 2D `a` de los ejemplos anteriores.

1. Quédate con todos los elementos de la última columna(5-55)

2. Quédate con los elementos 0,1,10 y 11

3. Quédate con los elementos 22,23 y 24

4. Quédate con la diagonal de la matriz. 

5. Pinta en pantalla todas las diagonales que estan por debajo y por encima de la diagonal principal. 

    [10 21 32 43 54]
    
    [20 31 42 53]
    
    [30 41 52]
    
    [40 51]
    
    [50]

---

    [5]
    
    [ 4 15]
    
    [ 3 14 25]
    
    [ 2 13 24 35]
    
    [ 1 12 23 34 45]
    
    
6. Quedate con los números pares de la fila 5.

7. Muesta la columna 1 en orden inverso y de 2 en 2 (50,30 y 10)

8. Todos los elementos de filas y columnas avanzando de 3 en 3:
    
    0,3,30,33
    
#### Solución:    

### <mark>9.2.1 Indexacion especial</mark>

La indexación especial permite **seleccionar filas o columnas enteras desordenadas.**


Vamos a montar un ejemplo para ver esta indexación de forma clara.

In [ ]:
#Creando una array de 10x10 de ceros
arr2d = np.zeros((10,10),dtype="I")
print(arr2d)

#Tamaño del array
arr_length = arr2d.shape[1]
print(f"Tamañao del array: {arr_length}")


# Creando una matriz con elementos que contienen el valor correspondiente a la posicion de la fila
for i in range(arr_length):
    arr2d[i] = i

print("\nMatriz del ejemplo:")
print(arr2d)

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]
Tamañao del array: 10

Matriz del ejemplo:
[[0 0 0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1 1 1]
 [2 2 2 2 2 2 2 2 2 2]
 [3 3 3 3 3 3 3 3 3 3]
 [4 4 4 4 4 4 4 4 4 4]
 [5 5 5 5 5 5 5 5 5 5]
 [6 6 6 6 6 6 6 6 6 6]
 [7 7 7 7 7 7 7 7 7 7]
 [8 8 8 8 8 8 8 8 8 8]
 [9 9 9 9 9 9 9 9 9 9]]


La indexacion especial permite:

In [ ]:
# sacar las filas 2, 4 , 6, 8
arr2d[[2,4,6,8]] # observa el uso de los dobles corchetes

array([[2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8]], dtype=uint32)

In [ ]:
#Permite cualquier orden
arr2d[[6,4,2,7]]

array([[6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7]], dtype=uint32)

Si qusieramos sacar columnas tendriamos que hacerlo así:

In [ ]:
arr2d[[0,1,2,3,4,5,6,7,8,9],[0]]#columna 0 al completo. Pongo los indices de las filas que quiero y el indice de la columna

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=uint32)

In [ ]:
arr2d[[list(range(10))],[0]]#columna 0 al completo. Pongo los indices de las filas que quiero y el indice de la columna

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]], dtype=uint32)

In [ ]:
arr2d

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]], dtype=uint32)

In [ ]:
arr2d[[0,1],[0,1]]#dos primeros elementos de la diagonal principal

array([0, 1], dtype=uint32)

### <div style = 'background-color:skyblue'> <center> EJERCICIO </div>

Utilizando la indexación especial, realiza las siguientes operaciones:

1. Recupera todos los elementos de la fila 3

2. Recupera todos los elementos de la columna 5

3. Quedate con los elementos de las posiciones 1, 3 y 5 de la columna 3.

4. Muestra los elementos de las posiciones 1, 3 y 5 de la fila 6.

5. De la fila 3 saca el tercer elemento y de la fila 4 saca el quinto.    

### <mark>9.3 Seleccion de valores que cumplan ciertas condiciones</mark>

Si deseamos seleccionar valores de un array que cumplan con ciertas condiciones, es sencillo con NumPy.

**Basta con poner entre los [ ] la condición o condiciones que queramos utilizar.**

También acepta operadores lógicos aunque en numpy:
* and = &
* or = |

Por ejemplo, comencemos con la siguiente matriz:

In [ ]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]



1) Selecciona todos los valores menores a 5

2) Selecciona todos los valores >=5 y menor o igual a 10

3) Selecciona todos los valores mayores que 11

In [ ]:
#1)
menores_5 = a[ a < 5]
print(menores_5)

[1 2 3 4]


In [ ]:
#podemos crear primero la condición y almacenarla en un array booleano

condi_menores_5 = (a < 5)
print(condi_menores_5)

#ahora usamos el array booleano para seleccionar los valores 
menores_5 = a[condi_menores_5]
print(menores_5)

[[ True  True  True  True]
 [False False False False]
 [False False False False]]
[1 2 3 4]


In [ ]:
#2 mayores o igual a 5 y menores o igual a 10
condi_2 = ((a >= 5) & (a <= 10))
print(condi_2)

seleccionados2 = a[condi_2]
print(seleccionados2)

[[False False False False]
 [ True  True  True  True]
 [ True  True False False]]
[ 5  6  7  8  9 10]


In [ ]:
# 3) mayores a 11
condi_3 = (a > 11)
print(condi_3)
seleccionados3 = a[condi_3]
print(seleccionados3)

[[False False False False]
 [False False False False]
 [False False False  True]]
[12]


**Más ejemplos**

Supongamos que queremos eliminar todas las apariciones de 6 del siguiente array. Veamos cómo hacer eso.

In [ ]:
arr = np.array([4,5,6,7,8,9,10,11,4,5,6,33,6,7])
print(arr)

[ 4  5  6  7  8  9 10 11  4  5  6 33  6  7]


In [ ]:
arr = np.array([4,5,6,7,8,9,10,11,4,5,6,33,6,7])
print(arr)

[ 4  5  6  7  8  9 10 11  4  5  6 33  6  7]


### <mark>9.4 Eliminar elementos por valor o condición usando np.argwhere () & np.delete ()</mark>

In [ ]:
#supongamos que tenemos el siguiente array
arr = np.array([4, 5, 6, 7, 8, 9, 10, 11, 4, 5, 6, 33, 6, 7])

In [ ]:
arr

array([ 4,  5,  6,  7,  8,  9, 10, 11,  4,  5,  6, 33,  6,  7])

Ahora eliminemos todas las apariciones de 6 del Array anterior usando np.argwhere () & np.delete ()

In [ ]:
indices_con_valor6 = np.argwhere(arr == 6)

In [ ]:
arr = np.delete(arr, indices_con_valor6)#en este caso ponemos == queremos que borre los elementos que sean iguales a 6
print('Array modificado :')
print(arr)

Array modificado :
[ 4  5  7  8  9 10 11  4  5 33  7]


**<div class="alert alert-info"> Importante: </div>**
    Lo que hace **np.argwhere es crear una Array de enteros** que luego utiliza delete para borrar solo aquellas posiciones.

In [ ]:
print(np.argwhere(arr == 7))

[[ 2]
 [10]]


### <mark>9.5 Broadcasting (Difusion)</mark>

Con las listas de python **no se pueden realizar operaciones elemento a elemento, pero con NumPy si se puede realizar.**

Vamos a ver como es el comportamiento de las listas ante las siguientes operaciones:

In [ ]:
# observar el comportamiento de las listas
lista = list(range(10))
print(lista)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [ ]:
lista + lista # este procedimento lo que hace es concatenar las listas

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
x = 3
lista*x # este procedimento hace que se repita la lista x numero de veces

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9]

Intentemos multiplicar cada elemento de la lista por 2

In [ ]:
lista * 2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

Nos duplica los elementos de la lista pero no mulplica por 2 cada elemento. Para hacerlo tendríamos que recorrer cada elemento y aplicarle la multiplicación. Pero qué ocurre con los arrays de Numpy?

In [ ]:
my_arr = np.array([1, 10, 20, 75])
my_arr

array([ 1, 10, 20, 75])

In [ ]:
#probar a multiplicarlo

Vemos que en este caso sí, nos duplica cada elemento.

**<div class="alert alert-success">Los arrays están optimizados para realizar una misma operación sobre todos sus elementos.</div>**


### <div style = 'background-color:skyblue'> <center> EJERCICIOS </div>

In [ ]:
b = np.array([
             [0,  1,  2,  3,  4,  5],
             [10, 11, 12, 13, 14, 15],
             [20, 11, 22, 23, 24, 25],
             [30, 11, 32, 33, 34, 35],
             [40, 41, 42, 43, 44, 45],
             [50, 51, 52, 43, 54, 55]
            ])

print(b)

[[ 0  1  2  3  4  5]
 [10 11 12 13 14 15]
 [20 11 22 23 24 25]
 [30 11 32 33 34 35]
 [40 41 42 43 44 45]
 [50 51 52 43 54 55]]


Dado el array b 2D. Realiza las operaciones que se indican a continuación.

**1. Quedate con los valores menores de 22.**


**2. De la columna 5, muestra únicamente los números que sean divisores de 7.**


**3. Quedate con los valores mayores a 22 y que sean menores de 33.**


**4. Elimina los valores 11 y 43. Almacena el resultado en un nuevo array.**


**5. Muestra los valores que sean multiplos de 9 ó de 7.**


**6. Del resultado obtenido en el punto 5, divide por 2 los 3 últimos valores.**



In [ ]:
#1)


In [ ]:
#2) Versión con mascara


In [ ]:
#2) version normal


In [ ]:
#3) mayores a 22 y menores a 33


In [ ]:
#4. Elimina los valores 11 y 43. Almacena el resultado en un nuevo array. 



In [ ]:
#5. Muestra los valores que sean multiplos de 9 ó de 7.


In [ ]:
# 6. Del resultado obtenido en el punto 5, divide por 2 los 3 últimos valores.


---
### 10. Remodelando Arrays - Manipulando dimensiones

### <mark>10.1 Reshape</mark>

Devuelve una vista de la matriz que contiene los mismos datos con una nueva distribucion. No modifica realmente la matriz.

![np_reshape.png](https://drive.google.com/uc?id=1ORutlpFrrWPqfXhDT-cG4wT27FfEss2t)

In [ ]:
data = np.arange(1,7)
print(data)
data.ndim

print(data.reshape(2,3))

print(data.reshape(3,2))

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [ ]:
data

array([1, 2, 3, 4, 5, 6])

In [ ]:
# arr es un vector de 25 elementos y se convertira en una matriz de 5x5
arr = np.arange(25) #Genera un array de numeros enteros del 0 al 24
print(arr)
print(f"Array con {arr.size} elementos organizados: {arr.shape}. Ahora queremos reorganizar la matriz en 5x5")
arr.reshape(5,5)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
Array con 25 elementos organizados: (25,). Ahora queremos reorganizar la matriz en 5x5


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
# Cambiando las dimensiones del array para que sea una matriz
# de una sola dimension horizontal (1 fila y 25 columnas)
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [ ]:
# de una sola dimension vertical (1 columna y 25 filas)
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [ ]:
arr.reshape(25,1).shape

(25, 1)

### <div style = 'background-color:skyblue'> <center> Ejercicio 10.1.1 </div>

**Crea un vector de 48 elementos aleatorios entre el 1 y el 99(incluido) y organizalos en un array 3D.**

* Prueba a guardar el reshape en un nuevo array llamado arr2.

* En arr2 modifica el primer elemento y ponle el valor 99

* Muestra en pantalla arr1 y arr2. ¿Qué ha pasado?

Nota: como pongas los 48 elementos a mano, me jubilo.

In [ ]:


#qué pasa si modificamos arr2, por ejemplo el primer valor arr2[0][0][0] = 99


#QUÉ HA PASADO???

### <mark>10.2 ravel y flatten</mark>

**Lo contrario de reshape, es la función `ravel y flatten`, es decir, eliminar todas las dimensiones y dejar un array plano.**


La principal diferencia entre los dos es que __flatten__ devuelve una copia y __ravel__ devuelve una vista, es decir, si hacemos un cambio en el array original, se verá reflejado en la variable asignada a ravel. 

Es importante recordar que los arrays son mutables, es decir, si no realizamos una copia correctamente, los dos arrays compartirán las mismas posiciones de memoria.

In [ ]:
arr2

array([[[99,  4,  6],
        [62, 53, 21],
        [ 3, 66, 14],
        [40, 73, 17]],

       [[34, 17, 78],
        [25, 95, 22],
        [72, 62, 91],
        [91, 71, 85]],

       [[43, 13, 68],
        [64, 70, 64],
        [74, 69, 50],
        [19, 61, 61]],

       [[52, 30, 90],
        [ 8, 89, 33],
        [74, 56, 24],
        [22, 35,  7]]])

In [ ]:
a = arr2.ravel()
print(a)
print(arr2)


[99  4  6 62 53 21  3 66 14 40 73 17 34 17 78 25 95 22 72 62 91 91 71 85
 43 13 68 64 70 64 74 69 50 19 61 61 52 30 90  8 89 33 74 56 24 22 35  7]
[[[99  4  6]
  [62 53 21]
  [ 3 66 14]
  [40 73 17]]

 [[34 17 78]
  [25 95 22]
  [72 62 91]
  [91 71 85]]

 [[43 13 68]
  [64 70 64]
  [74 69 50]
  [19 61 61]]

 [[52 30 90]
  [ 8 89 33]
  [74 56 24]
  [22 35  7]]]


In [ ]:
a[0]=0
print(a)
print(arr2)

[ 0 11 43 88 84 96  8 17 14 52 47 60 98 77  1 45 29 63 56 63 52  4 80 39
 89 32 10 19  5 77 95 70 51 42 18 59 78 81 72 83 45 96 58 25 60 49  2 96]
[[[ 0 11 43]
  [88 84 96]
  [ 8 17 14]
  [52 47 60]]

 [[98 77  1]
  [45 29 63]
  [56 63 52]
  [ 4 80 39]]

 [[89 32 10]
  [19  5 77]
  [95 70 51]
  [42 18 59]]

 [[78 81 72]
  [83 45 96]
  [58 25 60]
  [49  2 96]]]


In [ ]:
print(f"Antes de aplanar el array con ravel:\n{arr2}")
print(f"Aplanamos:\n{arr2.ravel()}")
print(f"Despues de aplanar el array con ravel:\n{arr2}")

Antes de aplanar el array con ravel:
[[[ 0 11 43]
  [88 84 96]
  [ 8 17 14]
  [52 47 60]]

 [[98 77  1]
  [45 29 63]
  [56 63 52]
  [ 4 80 39]]

 [[89 32 10]
  [19  5 77]
  [95 70 51]
  [42 18 59]]

 [[78 81 72]
  [83 45 96]
  [58 25 60]
  [49  2 96]]]
Aplanamos:
[ 0 11 43 88 84 96  8 17 14 52 47 60 98 77  1 45 29 63 56 63 52  4 80 39
 89 32 10 19  5 77 95 70 51 42 18 59 78 81 72 83 45 96 58 25 60 49  2 96]
Despues de aplanar el array con ravel:
[[[ 0 11 43]
  [88 84 96]
  [ 8 17 14]
  [52 47 60]]

 [[98 77  1]
  [45 29 63]
  [56 63 52]
  [ 4 80 39]]

 [[89 32 10]
  [19  5 77]
  [95 70 51]
  [42 18 59]]

 [[78 81 72]
  [83 45 96]
  [58 25 60]
  [49  2 96]]]


In [ ]:
print("Aplanamos arr2 que tiene estructura 4x4x3")
print(f"Arr2:\n{arr2}")
arr3 = arr2.flatten()
print("Resultado de aplanar arr2:")
print(arr3)

Aplanamos arr2 que tiene estructura 4x4x3
Arr2:
[[[99  4  6]
  [62 53 21]
  [ 3 66 14]
  [40 73 17]]

 [[34 17 78]
  [25 95 22]
  [72 62 91]
  [91 71 85]]

 [[43 13 68]
  [64 70 64]
  [74 69 50]
  [19 61 61]]

 [[52 30 90]
  [ 8 89 33]
  [74 56 24]
  [22 35  7]]]
Resultado de aplanar arr2:
[99  4  6 62 53 21  3 66 14 40 73 17 34 17 78 25 95 22 72 62 91 91 71 85
 43 13 68 64 70 64 74 69 50 19 61 61 52 30 90  8 89 33 74 56 24 22 35  7]


In [ ]:
#Si modifico el primer elemento de arr3, cambiaré también arr1?
print("Ahora vamos a comprobar que arr3 es una copia independiente de arr2. Vamos a modificar el primer elemento de arr3 con un -1")
arr3[0]= -1

print(f"Arr2:\n{arr2}")
print(f"Arr3:\n{arr3}")

Ahora vamos a comprobar que arr3 es una copia independiente de arr2. Vamos a modificar el primer elemento de arr3 con un -1
Arr2:
[[[99  4  6]
  [62 53 21]
  [ 3 66 14]
  [40 73 17]]

 [[34 17 78]
  [25 95 22]
  [72 62 91]
  [91 71 85]]

 [[43 13 68]
  [64 70 64]
  [74 69 50]
  [19 61 61]]

 [[52 30 90]
  [ 8 89 33]
  [74 56 24]
  [22 35  7]]]
Arr3:
[-1  4  6 62 53 21  3 66 14 40 73 17 34 17 78 25 95 22 72 62 91 91 71 85
 43 13 68 64 70 64 74 69 50 19 61 61 52 30 90  8 89 33 74 56 24 22 35  7]


Como vemos, arr2 y arr3 son independientes, **porque flatten hace una copia completa.**

### Pregunta 

¿Es posible reestructurar el siguiente array?

In [ ]:
preg_uno = np.random.randint(1,100,11)
preg_uno

### Pregunta 

¿Es posible reestructurar el siguiente array en la estructura? `(4, 2)`

In [ ]:
preg_dos = np.array([
    [10, 30, 45, 150],
    [12, 40, 20, 10]
])

### <div style = 'background-color:skyblue'> <center> Ejercicio 10.2.1 </div>
Escribe un Array 2D con los números del 100 al 112 (si es posible)

#### Solución

---
### 11. Convertir Arrays 1D en Arrays 2D (agregar un nuevo eje a un Array)

Para aumentar las dimensiones de nuestros Arrays, podemos usar: 

* **np.newaxis**

* **np.expand_dims** 


### <mark>np.newaxis</mark>

El uso **np.newaxis aumentará las dimensiones del Array en una dimensión cuando se use una vez.** Esto significa que un Array 1D se convertirá en un Array 2D , un Array 2D se convertirá en un Array 3D , y así sucesivamente.

Hagamos algunos ejemplos:

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6])
print(a.shape)
print(a)

(6,)
[1 2 3 4 5 6]


In [ ]:
#Podemos usar np.newaxis para agregar un nuevo eje:

a2 = a[np.newaxis, :]#dentro del corchete creo el nuevo eje y separado por coma el vector de inicio a fin(por eso los :)
print(a2.shape)
print(a2)

(1, 6)
[[1 2 3 4 5 6]]


Por ejemplo, podemos convertir un Array 1D en un vector de fila insertando un eje a lo largo de la primera dimensión:

In [ ]:
row_vector = a[np.newaxis, :]
print(row_vector.shape)
print(row_vector)

(1, 6)
[[1 2 3 4 5 6]]


O, para un vector de columna, poedemos insertar un eje a lo largo de la segunda dimensión:

In [ ]:
col_vector = a[:, np.newaxis]
print(col_vector.shape)
print(col_vector)

(6, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


### <mark>np.expand_dims</mark>

También podemos expandir un array insertando un nuevo eje en una posición específica.

In [ ]:
#Por ejemplo, si empezamos con este array:

a = np.array([1, 2, 3, 4, 5, 6])
print(a.shape)

(6,)


In [ ]:
#para agregar un eje en la posición de índice 1 con:

b = np.expand_dims(a, axis=1)
print(b.shape)
print(b)

(6, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [ ]:
#Podemos agregar un eje en la posición de índice 0 con:

c = np.expand_dims(a, axis=0)
print(c.shape)
print(c)

(1, 6)
[[1 2 3 4 5 6]]


---
### 12. Crear un Array a partir de datos existentes

Partiendo de un Array tenemos diversas formas de crear otros Arrays.

1. A partir de una sección de un array existente usando **slicing**


2. Apilando horizontal o verticalmente otros arrays con **vstack y hstack**


3. Podemos dividir un Array en varios Arrays más pequeños usando **hsplit.**


Tienes esta matriz:

In [ ]:
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### <mark>Usando slicing</mark>

In [ ]:
arr1 = a[3:8].copy()
arr1 #Sección de su matriz desde la posición de índice 3 hasta la posición de índice 8.

array([4, 5, 6])

In [ ]:
arr1[0]=-1

In [ ]:
print(a)
print(arr1)

[1 2 3 4 5 6]
[-1  5  6]


### <mark>Apilando</mark>

In [ ]:
a1 = np.array([[1, 1],
               [2, 2]])

a2 = np.array([[3, 3],
               [4, 4]])

In [ ]:
a3= np.vstack((a1, a2))
a3

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [ ]:
a4 = np.hstack((a1, a2))
a4

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [ ]:
a4[0][0] = -1

In [ ]:
print(a1)
print(a2)


[[1 1]
 [2 2]]
[[3 3]
 [4 4]]


In [ ]:
#vemos que a4 es una copia independiente, ya que los cambios de elementos no afectan a las matrices originales
print(a4)

[[-1  1  3  3]
 [ 2  2  4  4]]


### <mark>Dividiendo Arrays con split(...) ycon hsplit(...)</mark>


### Split(...)

Usamos la función **split** para dividir un array en multiples sub-arrays horizontalmente. Por defecto axis viene a 0.

La forma de usarlo es:

**numpy.split(ary, indices_or_sections, axis=0)**

In [ ]:
arr = np.arange(1,13).reshape(3,4)
print(arr)
print(arr.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)


Cortamos en 3 trozos

In [ ]:
a = np.split(arr, 3)
a

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]]), array([[ 9, 10, 11, 12]])]

In [ ]:
a[0]

array([[1, 2, 3, 4]])

In [ ]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

**Ahora cortamos por secciones. Vamos a quedarnos con las secciones [1,3] equivaldria a:**

[:1] -->Desde el inicio hasta el 1 sin incluirlo (osea seria la fila 0)

[1:3] --> Desde la fila 1 hasta la fila 3 sin incluirla ( serian las filas 1 y 2)

[3:] --> Desde la fila 3 hasta el final (como no hay fila 3, saldrá vacía)

In [ ]:
a = np.split(arr, [1,3])
a

[array([[1, 2, 3, 4]]),
 array([[ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]),
 array([], shape=(0, 4), dtype=int32)]

**Vamos a hacer otro ejemplo**

In [ ]:
arr = np.arange(1,25).reshape(6,4)
print(arr)
print(arr.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
(6, 4)


### Hsplit(...)

La función **hsplit()** se usa para dividir un Array en múltiples sub-Arrays verticalmente (en forma de columna).
hsplit es equivalente a dividir con axis = 1, el Array siempre se divide a lo largo del segundo eje, independientemente de la dimensión de este.

La forma de usarlo es:

**numpy.hsplit(array, índices_o_secciones)**

In [ ]:
x = np.arange(0,6).reshape(3,2)
print(x)

a = np.hsplit(x,2)
print(a)
#podemos acceder a cada trozo cortado por su indice...

[[0 1]
 [2 3]
 [4 5]]
[array([[0],
       [2],
       [4]]), array([[1],
       [3],
       [5]])]


![numpy-manipulation-array-hsplit-function-image-a.png](https://drive.google.com/uc?id=100-SpRodAhmpbj6T7ekHw_ui2-WO9V9q)

In [ ]:
a = np.arange(16).reshape(4,4)
print(a)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [ ]:
np.hsplit(a, 2)

![numpy-manipulation-array-hsplit-function-image-2.png](https://drive.google.com/uc?id=1rH9rpFoRmE3kFEN3EBDcl2pv6PHdLrWq)

In [ ]:
x = np.arange(1, 25).reshape(2, 12)#creamos una matriz de 2x12
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

Si quisieramos dividir esta matriz en tres matrices de igual forma, ejecutaría:

In [ ]:
x1 = np.hsplit(x, 3)
x1

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

Dividir nuestra matriz después de la tercera y cuarta columna, ejecutaríamos:

In [ ]:
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [ ]:
x2 = np.hsplit(x, (3, 4))# (3,4) --> [:3] [3:4] [4:]
x2

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

### <mark>Vistas</mark>

¡Las vistas son un concepto importante de NumPy! 

Las funciones NumPy, así como operaciones como la indexación y el corte, **devolverán vistas** siempre que sea posible. **Esto ahorra memoria y es más rápido (no es necesario realizar ninguna copia de los datos).** Sin embargo, es importante tener esto en cuenta: 

**<div class="alert alert-danger">¡Modificar datos en una vista también modifica la matriz original!</div>**

Vamos a ver esto con un ejemplo práctico. Creemos la siguiente matriz de 12 elementos:

In [ ]:
a = np.arange(1, 13).reshape(3, 4)#creamos una matriz de 2x12
a

Ahora creamos una matriz b1 cortando a y modificando el primer elemento de b1. 

In [ ]:
b1 = a[0,:]
print(b1)
#asigna el valor 99 a la primera posición del array b1

**¿Qué ha ocurrido en a y b1? Compruebalo**

El uso del método **copy hará una copia completa del Array y sus datos (una copia profunda ).** Para usar esto podemos ejecutar:


In [ ]:
b2 = a[0].copy()
print(b2)

b2[0]= 99

#comprueba qué ocurre en a y en b2


### <div style = 'background-color:skyblue'> <center> EJERCICIOS </div>
    
1. Crea una `matriz 4x4` con números aleatorios entre 0 y 70 denominada x.
    
2. Quédate con los 3 últimos valores de la segunda fila y con los 2 primeros de la última columna. Demonomina estos nuevos arrays como `x1 y x2.`
    
3. Modifica el primer elemento de x1 y x2 para que contenga un número par entre el 0-10. Asegurate que el array `x` no se vea afectado.
    
4. Crea 2 nuevos arrays denominados `y1 e y2.`
    
    1. y1 sera un array 3x3 de números distribuidos uniformemente.
    
    2. y2 será un array 3x3 de unos.
    
5. Apila y1 e y2 vertical y horizontalmente.    
    
6. División de array x:
    
    1. Divídelo en 4 filas.
    
    1. Divídelo en dos partes. Desde el inicio hasta la primera fila y luego el resto.
    
    2. Divídelo después de la primera y segunda columnas.
   

### 13. Operaciones con NumPy

Existen muchas operaciones que podemos realizar sobre arrays. Las vamos a agrupar en 3 bloques:

1. **Aritmética**

2. **Estadística**

3. **Operaciones de Matrices**


### <mark>13.1 Aritmética</mark>

* Suma <code>**sum**</code>

Es importante enfatizar en la importancia de saber sobre qué eje ( *axis* ) de los arrays queremos realizar la suma.

In [ ]:
e = np.array([[[1, 0], [0, 0]],
              [[1, 1], [1, 0]],
              [[1, 0], [0, 1]]]
            )

print(e)
e.sum(axis = 0)


[[[1 0]
  [0 0]]

 [[1 1]
  [1 0]]

 [[1 0]
  [0 1]]]


array([[3, 1],
       [1, 1]])

El resultado significa que sumando las columnas del primer componente que es:

[1. 0]

[1, 1]

[1, 0]


Obtenemos que las filas en la columna suman 3 y en la segunda columna 1, por lo tanto [3, 1]

En el segundo componente que es:

[0, 0]

[1, 0]

[0, 1]

Obtenemos que las filas de la primera columna suman 1 y de la segunda 1 también, por lo tanto [1, 1]

In [ ]:
e.sum(axis=1)

En este caso cada dimensión, funciona a nivel de fila, por lo tanto, si sumamos la primera fila que sería [1 + 0], [0 + 0] = [1, 0]

La segunda fila: [1 + 1], [1 + 0] = [2, 1]

La tercera: [1 + 0], [0 + 1] = [1, 1]

Si no especificamos su eje, se calcula de forma global.

In [ ]:
e.sum()

6

In [ ]:
print('Filas ', e.sum(axis=0))
print('Columnas ', e.sum(axis=1))
print('Total ', e.sum())

Filas  [[3 1]
 [1 1]]
Columnas  [[1 0]
 [2 1]
 [1 1]]
Total  6


* <code>**round**</code>: **Permite redondear a n decimales todo un array.**

In [ ]:
rand = np.random.rand(10)
print(rand)
rand.round(2)

[0.79888044 0.82313607 0.06729162 0.43182498 0.68863858 0.11373443
 0.52135968 0.06720909 0.35253482 0.95106159]


array([0.8 , 0.82, 0.07, 0.43, 0.69, 0.11, 0.52, 0.07, 0.35, 0.95])

* <code>**fill**</code>: **Permite rellenar un array con un valor pasado por parámetro.**

In [ ]:
zero_array = np.zeros(20)#creamos un array 1D de 20 ceros
print(zero_array)
zero_array[5:15].fill(5)#rellenamos las posiciones 5-14 con cincos.
zero_array

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


array([0., 0., 0., 0., 0., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 0., 0.,
       0., 0., 0.])

* **Suma elemento a elemento de un array.**

**Sumamos el mismo array**

In [ ]:
arr = np.arange(0,10) # crear un array de 10 elementos
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr + arr # Suma elemento a elemento de los arrays

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

---
**Sumamos dos arrays 1D de distinto tamaño**

In [ ]:
# Suma de valores uno a uno con arrays
aa = np.arange(5)
print(aa)
bb = np.arange(10) # este array es mas grande que el anterior
print(bb)
aa+bb[:5] # deben tener el mismo tamaño para realizar la suma

[0 1 2 3 4]
[0 1 2 3 4 5 6 7 8 9]


array([0, 2, 4, 6, 8])

---
**Sumamos Arrays 2D**

In [ ]:
data = np.array([[1, 2], [3, 4]])
ones = np.array([[1, 1], [1, 1]])
data + ones

array([[2, 3],
       [4, 5]])

![np_matrix_arithmetic.png](https://drive.google.com/uc?id=1vRH9AjrVyf4QrZkjJhh8csowt3eIGbTA)

Puedes realizar estas operaciones aritméticas en matrices de diferentes tamaños, pero **solo si una matriz tiene solo una columna o una fila.** 

In [ ]:
data = np.array([[1, 2], [3, 4], [5, 6]])
ones_row = np.array([[1, 1]])
data + ones_row

array([[2, 3],
       [4, 5],
       [6, 7]])

![np_matrix_broadcasting.png](https://drive.google.com/uc?id=162iy8pKULsf0v3a4FjyFyz-mZkHeRYdS)

* **Multiplicacion elemento a elemento**

In [ ]:
arr * arr 

* **Resta elemento a elemento**

In [ ]:
arr - arr

* **División elemento a elemento**

In [ ]:
# Mensaje de advertencia si se presenta una division por cero, pero no hay error!
# solo se reemplazo por el valor nan
arr/arr # division elemento a elemento

* **Raiz cuadrada de cada elemento**

In [ ]:
#Calcular la raiz cuadrada de cada elemento
np.sqrt(arr)

* **Valor absoluto de cada elemento**

In [ ]:
np.abs(arr)

### <mark>13.2 Estadística</mark>

* **Desviacion estandar**

En estadística, la desviación típica (también conocida como desviación estándar y desvío típico y representada de manera abreviada por la letra griega minúscula **gma σ o la letra latina s, así como por las siglas SD (de standard deviation).** 


* **Es una medida que se utiliza para cuantificar la variación o la dispersión de un conjunto de datos numéricos.1**


* **Una desviación estándar baja** indica que la mayor parte de los datos de una muestra **tienden a estar agrupados cerca de su media** (también denominada el valor esperado), mientras que una **desviación estándar alta** indica que los datos se extienden sobre un **rango de valores más amplio.**

![Standard_deviation_diagram.png](https://drive.google.com/uc?id=1L26RPEcg7kGxlJ_pwTfyw-c5rhie1otO)

In [ ]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Desviacion estandar
np.std(arr)# en este caso vemos que tiene una desviación elevada, casi de 3, alejandose mucho de su media.

2.8722813232690143

* **Media** - <code>**mean**</code>: 

Realiza la media del array o por uno de sus ejes.



In [ ]:
e

array([[[1, 0],
        [0, 0]],

       [[1, 1],
        [1, 0]],

       [[1, 0],
        [0, 1]]])

In [ ]:
e.mean(axis = 0)

array([[1.        , 0.33333333],
       [0.33333333, 0.33333333]])

In [ ]:
e.mean(axis = 1)

array([[0.5, 0. ],
       [1. , 0.5],
       [0.5, 0.5]])

In [ ]:
e.mean()#la media de todo el array

0.5

In [ ]:
arr.mean()

4.5

* **Mediana** - `median`:

En el ámbito de la estadística, la mediana representa el valor de la variable de posición central en un conjunto de datos ordenados. Se le denota mediana.

Si la serie tiene un número par de puntuaciones, la mediana es la media entre las dos puntuaciones centrales.

Ejemplo.

7, 8, 9, 10, 11, 12

Mediana = 9,5 = (9+10)/2

In [ ]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
print(arr)
np.median(arr)

[0 1 2 3 4 5 6 7 8 9]


4.5

* **Varianza** - `var`:

La varianza es una **medida de dispersión** que representa la **variabilidad de una serie de datos respecto a su media.**

In [ ]:
np.var(arr)

8.25

### <mark>13.3 Operaciones de Matrices</mark>

In [ ]:
#creacion de una matriz de ejemplo
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

* **Trasponer una Matriz**

Las matrices NumPy tienen la propiedad Tque le permite transponer una matriz.

![np_transposing_reshaping.png](https://drive.google.com/uc?id=1qxFf43Cv2DewTUlEvbw5vCy_k9yfD8T7)

In [ ]:
# transpuesta de una matriz
arr_2d.T # tambien puede ser arr_2d.transpose()

array([[ 5, 20, 35],
       [10, 25, 40],
       [15, 30, 45]])

* **Inversa de una matriz**

La función de NumPy nos **np.flip()** permite voltear o invertir el contenido de una matriz a lo largo de un eje. Cuando usemos np.flip(), hay que especificar la matriz que le gustaría invertir y el eje. Si no se especifica el eje, NumPy invertirá el contenido a lo largo de todos los ejes de la matriz de entrada.

In [ ]:
#Array 1D
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
reversed_arr = np.flip(arr)
print(reversed_arr)

[8 7 6 5 4 3 2 1]


Invertimos todos son ejes

In [ ]:
#Array 2D
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(arr_2d)
reversed_arr = np.flip(arr_2d)
print(reversed_arr)
#no hemos especificado ejes y ha invertido los valores en todos los ejes
#primero invierte las filas y de ese resultado invierte las columnas.

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


Invertimos solo las filas

In [ ]:
reversed_arr_rows = np.flip(arr_2d, axis=0)
print(reversed_arr_rows)

[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


 Invertir solo las columnas con:

In [ ]:
reversed_arr_columns = np.flip(arr_2d, axis=1)
print(reversed_arr_columns)

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]


También podemeos invertir el contenido de una sola columna o fila. Por ejemplo, puede invertir el contenido de la fila en la posición de índice 1 (la segunda fila):

In [ ]:
arr_2d[1] = np.flip(arr_2d[1])
print(arr_2d)

#es equivalente a:
fila1_inversa = arr_2d[1, ::-1]
print(fila1_inversa)

También podemos invertir la columna en la posición de índice 1 (la segunda columna):

In [ ]:
print(arr_2d)
arr_2d[:,1] = np.flip(arr_2d[:,1])
print(arr_2d)

#es equivalente a:
columna1_inversa = arr_2d[::-1, 1]
print(columna1_inversa)

---
### <div style = 'background-color:skyblue'> <center> EJERCICIOS </div>

![ejercicios.jpg](https://drive.google.com/uc?id=17e8jXVq7hJd1BkBzR_Pd7yz0Ql2vo_Ij)

### Ejercicio 1

Crea un Array 2D de 25 números aleatorios entre los 100 primeros números.

1) Pinta la matriz resultante.

2) De la matriz generada, quedate con los valores que sean múltiplos de 5.

3) Quedate con todos los valores pares o impares menores de 10.

4) Quedate con los valores que sean multiplos de 3 y que sean impares mayores de 20.

5) Une todos los resultados de los apartados 2-4 en un nuevo array 1D quedandote solo con los valores únicos.

6) Reestructura el array para convertirlo en uno 2D con tantas filas como elementos tenga.

7) Del nuevo array 2D, muestra su estructura, dimensiones y número de elementos

In [ ]:
#1) Crea un Array 2D de 25 números aleatorios entre los 100 primeros números
import numpy as np

matriz = np.random.randint(0, 100, size=(5, 5))
print(matriz)

In [ ]:
#2) Múltiplos de 5
multiplos5 = matriz[matriz % 5 == 0]
print("Múltiplos de 5:", multiplos5)

In [ ]:
#3) Valores pares o impares menores de 10
menores10 = matriz[matriz < 10]
print("Pares o impares menores de 10:", menores10)

In [ ]:
#4) Múltiplos de 3 que sean impares mayores de 20
resultado4 = matriz[(matriz % 3 == 0) & (matriz % 2 != 0) & (matriz > 20)]
print("Múltiplos de 3, impares y mayores de 20:", resultado4)

In [ ]:
#5) Une todos los resultados de los apartados 2-4 en un nuevo array 1D con valores únicos
union = np.unique(np.concatenate([multiplos5, menores10, resultado4]))
print("Array unido con valores únicos:", union)

In [ ]:
#6) Reestructura el array para que sea 2D, con tantas filas como elementos tenga
array2d = union.reshape(-1, 1)
print(array2d)

In [ ]:
#7) Muestra la estructura, dimensiones y número de elementos del array
print("Estructura (shape):", array2d.shape)
print("Dimensiones (ndim):", array2d.ndim)
print("Número de elementos (size):", array2d.size)

### Ejercicio 2

Escribe un programa que genere una matriz de 10x10, en la que sus elementos en los bordes sean 1 y sus elementos interiores sean 0.

#### Solución

### Ejercicio 3

Escribe una función que reciba un array de valores para convertir los valores de grados centígrados en grados Fahrenheit y viceversa. 

Arrays de pruebas:

**Valores en grados Fahrenheit [0, 12, 45.21, 34, 99.91]**

**Valores en grados Centígrados [-17.78, -11.11, 7.34, 1.11, 37.73, 0. ]**

La formula para convertir unos grados en otros es:

![conversion_grados.PNG](https://drive.google.com/uc?id=1ijiM-nN6I9FrDmojx-dZRWPgYIyzGbFv)

Elabora un programa de pruebas que pregunte al usuario la conversión que quiere realizar y en función de ello cargue un array de temperaturas u otro.

In [ ]:
#define aquí la función
    

### Ejercicio 4

1. Crea los siguientes Arrays:

    * a será un array 2D con valores aleatorios normales y estructura 3x3.

    * b será un array 1D con 3 elementos aletarorios entre 3-6.    

2. Suma los dos arrays y al resultado aplicale la raiz cuadrada.

3. Redondea el array resultante a dos decimales.

4. Crea un array denominado c que sea 2D 5x5 con números aleatorios entre 0-60.

5. Ordena cada fila.

6. Aplica la inversa:

    * A cada fila del array resultante del apartado 5.
    * A cada columna.
    * A toda la matriz

7. Saca la matriz traspuesta de c.

In [ ]:
#1) Crea un array 'a' de 3x3 con valores aleatorios de distribución normal
#   y un array 'b' de 1D con 3 elementos aleatorios entre 3 y 6
a = np.random.randn(3, 3)
b = np.random.randint(3, 7, size=3)
print("Array a (3x3 normal):")
print(a)
print("\nArray b (1D randint 3-6):")
print(b)

In [ ]:
#2) Suma a + b y aplica la raíz cuadrada al resultado
suma = a + b
raiz = np.sqrt(np.abs(suma))  # abs para evitar raíz de negativos
print("Suma a + b:")
print(suma)
print("\nRaíz cuadrada de la suma:")
print(raiz)

In [ ]:
#3) Redondea a 2 decimales
raiz_redondeada = np.round(raiz, 2)
print("Raíz cuadrada redondeada a 2 decimales:")
print(raiz_redondeada)

In [ ]:
#4) Crea un array 'c' de 5x5 con valores aleatorios entre 0 y 60
c = np.random.randint(0, 61, size=(5, 5))
print("Array c (5x5 randint 0-60):")
print(c)

In [ ]:
#5) Ordena cada fila del array c
c_ordenado = np.sort(c, axis=1)
print("Array c con filas ordenadas:")
print(c_ordenado)

In [ ]:
#6) Aplica flip a filas, columnas y a toda la matriz
flip_filas = np.flip(c, axis=1)
flip_columnas = np.flip(c, axis=0)
flip_total = np.flip(c)
print("Flip filas (eje 1):")
print(flip_filas)
print("\nFlip columnas (eje 0):")
print(flip_columnas)
print("\nFlip total:")
print(flip_total)

In [ ]:
#7) Transpuesta de c
c_transpuesta = c.T
print("Transpuesta de c:")
print(c_transpuesta)

### Ejercicio 5

Escribe una función para encontrar la unión de dos arrays 1D. 

La unión devolverá la matriz única y ordenada de valores que se encuentran en cualquiera de los dos arrays de entrada.

La función recibirá 2 parámetros con los arrays y retornará un nuevo array con la unión de ambos.

Antes de realizar cualquier operación se comprobará que los dos arrays tienen la misma dimensión, en caso de no ser así, aplanarán para convertirlos en 1D.